### ISSUE TITLE
Add template kubernetes 

### ISSUE THREAD

**Issue by NizarSteria** [FatmaAouissaoui/ProjectAngular#2]
**Templates**:
   

>  base
>     overlays
>     scripts

![image](https://user-images.githubusercontent.com/1705397/175261528-7a4945d9-dda9-4603-82a4-f6309a8bdbde.png)

**Comment by NizarSteria** [comment]
base:

> code-application-service.yml

```
apiVersion: v1
kind: Service
metadata:
  name: @@APP_MS_NAME@@-service
spec:
  type: ClusterIP
  ports:
    - name: http
      port: @@SERVICE_NAME_PORT@@
      targetPort: @@SERVICE_NAME_POD_PORT@@
  selector:
    app: @@APP_MS_NAME@@

```
